<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <ItemDefinitionGroup>
    <ClCompile>
      <!-- Assimp のインクルードディレクトリ -->
      <AdditionalIncludeDirectories>$(ProjectDir)external\assimp;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <!-- Assimp のライブラリディレクトリ -->
      <AdditionalLibraryDirectories>$(ProjectDir)lib\assimp\$(Configuration);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <!-- Assimp の依存ファイル -->
      <AdditionalDependencies>assimp-vc143-mt.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>